#!/bin/bash
#PBS -l nodes=1:ppn=9:xk
#PBS -l walltime=01:00:00
#PBS -N draw
#PBS -e /u/training/tra216/scratch/hw8/draw.err
#PBS -o /u/training/tra216/scratch/hw8/draw.out
# -m and -M set up mail messages at begin,end,abort:
# -m bea
# -M junyiz4@illinois.edu
cd /u/training/tra216/scratch/hw8
#. /opt/modules/default/init/bash
module load python/2.0.0
#module load cudatoolkit
aprun -n 1 -N 1 python Draw.py
