#!/bin/bash
#PBS -l nodes=1:ppn=16:xk
#PBS -N perturb
#PBS -l walltime=00:06:00
#PBS -e /u/training/tra216/scratch/hw7/sync_features.err
#PBS -o /u/training/tra216/scratch/hw7/sync_features.out
#PBS -M junyiz4@illinois.edu
cd /u/training/tra216/scratch/hw7
. /opt/modules/default/init/bash
module load bwpy/2.0.0-pre2
module load cudatoolkit
aprun -n 1 -N 1 python sync_features.py --extract_features 8
